public with sharing class DisplayBoardColorSettings {
	
	public String q1;
    public String q2;
    public String q3;
    public String q4;
    
    public String mode; // used if mode value is empty
    
    public String cng;
    public String diesel;
    public String baehybrid; 
    public String allisonhybrid;
    public String electric;
    
    public String emptySlot; 
    public String holiday;
    public String shutdown; 
    
    public String scheduledWeekHeader;
    public String weekHeaderOverbooked;
    public String unscheduledWeekHeader;
    
    public String toolBar;
    public String titleBar;
    public String futureHoldingsWeek;
    
    public String toolBarDirty;
    public String toolBarHistory;
    
    public String slotSelected;
    public String reserved;
    public String scheduled;
    public String futureHolding;
    // public String firm; 
 
 	public String weekHeaderFont;
 	
 	public String pageBackGround;
    
}